version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:

  webapp:
    build:
      context: .
      dockerfile: ExamCardSeller/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - PAYSTASK_SECRET=${PAYSTASK_SECRET}
      - PaystackSettings__ApiKey=${PaystackSettings__ApiKey}
      - PaystackSettings__BaseUrl=${PaystackSettings__BaseUrl}
      - PaystackSettings__Callback=${PaystackSettings__Callback}
    ports:
      - "5005:8080"
    networks:
      - mynetwork
