version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:

  webapp:
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
    ports:
      - "5000:80"
    networks:
      - mynetwork
